const books = {
  "luat-kinh-te": {
    title: "Luật Kinh tế",
    author: "PSG.TS Phan Thị Hồng",
    publisher: "Nhà xuất bản Đại học Quốc gia",
    type: "Giáo trình",
    genre: "Kinh tế",
    desc: "Giáo trình cung cấp nền tảng pháp lý cho hoạt động kinh tế và doanh nghiệp.",
    summary: "Cuốn sách hệ thống hóa toàn diện Bộ Luật Kinh tế và các nghị định hướng dẫn. Mỗi chương đi kèm ví dụ thực tế về hợp đồng, thuế và xử lý tranh chấp doanh nghiệp. Phân tích rõ ràng quyền và nghĩa vụ của các bên tham gia thị trường. Có chú giải các thuật ngữ pháp lý quan trọng giúp đọc giả dễ nắm bắt.",
    location: "Tầng 2 – Kệ sách A3 (Pháp luật)",
    status: "Sẵn có (Còn 45 cuốn)",
    image: "image/luật kinh tế.jpg"
  },
  "tu-dien-kinh-te": {
    title: "Từ điển Kinh tế học Anh - Việt",
    author: "MBA. Nguyễn Văn Dung",
    publisher: "Nhà xuất bản Lao động",
    type: "Sách tham khảo",
    genre: "Kinh tế học",
    desc: "Công cụ tra cứu chuyên sâu: cung cấp hàng nghìn thuật ngữ song ngữ Anh - Việt về Kinh tế học.",
    summary: "Bộ từ điển đầy đủ với hơn 5.000 mục từ song ngữ, giải thích các khái niệm kinh tế, tài chính và quản trị. Đặc biệt phù hợp cho sinh viên, nghiên cứu sinh và nhà kinh doanh cần tra cứu nhanh.",
    location: "Tầng 2 – Kệ sách A1 (Khu vực sách tra cứu/Từ điển)",
    status: "Sẵn có (Còn 48 cuốn)",
    image: "image/từ điển kinh tế học.jpg"
  },
  "nen-kinh-te-tu-do": {
    title: "Nền Kinh tế Tự do",
    author: "Marion McCrory",
    publisher: "Nhà xuất bản Kinh tế",
    type: "Sách tham khảo",
    genre: "Kinh tế",
    desc: "Phân tích các nguyên lý của nền kinh tế tự do và cơ chế thị trường.",
    summary: "Cuốn sách giải thích tường tận cách thị trường tự điều chỉnh thông qua cung và cầu. Mô tả vai trò nhà nước và các chính sách can thiệp trong từng bối cảnh kinh tế. Nhiều ví dụ minh họa từ lịch sử và các quốc gia đang phát triển. Đưa ra bài tập gợi mở để người đọc rèn luyện tư duy phân tích.",
    location: "Tầng 2 – Kệ sách A2 (Kinh tế vi mô)",
    status: "Sẵn có (Còn 43 cuốn)",
    image: "image/nền kinh tế tự do.jpg"
  },
  "cach-nen-kinh-te-van-hanh": {
    title: "Cách Nền Kinh Tế Vận Hành",
    author: "Roger E. A. Farmer",
    publisher: "Nhà xuất bản Kinh tế",
    type: "Sách tham khảo",
    genre: "Kinh tế",
    desc: "Giải thích cách các nền kinh tế vận hành và những yếu tố quyết định thành công.",
    summary: "Mô tả rõ ràng các động lực điều hành nền kinh tế vĩ mô và mối quan hệ giữa chính sách tiền tệ, tài khóa và tăng trưởng. Bao gồm các mô hình kinh tế quan trọng như IS-LM, AD-AS, và chu kỳ kinh doanh. Minh họa bằng số liệu thực tế và phân tích các cuộc khủng hoảng kinh tế. Cung cấp bài tập tình huống và phương pháp áp dụng cho lập kế hoạch kinh tế.",
    location: "Tầng 2 – Kệ sách A2 (Kinh tế vĩ mô)",
    status: "Sẵn có (Còn 47 cuốn)",
    image: "image/cách nền kinh tế vận hành.jpg"
  },
  "marketing-5-0": {
    title: "Marketing 5.0",
    author: "Philip Kotler",
    publisher: "Nhà xuất bản Kinh doanh",
    type: "Sách tham khảo",
    genre: "Marketing",
    desc: "Chiến lược marketing trong kỷ nguyên số, kết hợp AI và dữ liệu lớn.",
    summary: "Phân tích xu hướng marketing 5.0 với các công cụ AI, dữ liệu lớn và trải nghiệm số; kèm các case study từ các thương hiệu toàn cầu.",
    location: "Tầng 2 – Kệ sách M1 (Marketing)",
    status: "Sẵn có (Còn 46 cuốn)",
    image: "image/Marketing 5.0.jpg"
  },
  "quan-tri-marketing": {
    title: "Quản trị Marketing",
    author: "Kotler Keller",
    publisher: "Nhà xuất bản Giáo dục",
    type: "Giáo trình",
    genre: "Marketing",
    desc: "Giáo trình cung cấp các công cụ quản trị marketing từ cơ bản đến nâng cao.",
    summary: "Tổng hợp phương pháp phân tích thị trường, quản lý sản phẩm và triển khai chiến dịch hiệu quả, kèm các mẫu kế hoạch marketing và chuẩn đánh giá.",
    location: "Tầng 2 – Kệ sách M1 (Marketing)",
    status: "Sẵn có (Còn 44 cuốn)",
    image: "image/quản trị marketing.jpg"
  },
  "kinh-te-vi-mo": {
    title: "Kinh tế Vĩ mô",
    author: "Trần Văn B",
    publisher: "Nhà xuất bản Kinh tế TP.Hồ Chí Minh",
    type: "Giáo trình",
    genre: "Kinh tế vĩ mô",
    desc: "Giải thích các chỉ số vĩ mô quan trọng và ảnh hưởng của chính sách kinh tế.",
    summary: "Giải thích chi tiết các chỉ số vĩ mô, cách đo lường và tác động của chính sách tiền tệ, tài khóa đến nền kinh tế. Kèm biểu đồ và bài tập mẫu.",
    location: "Tầng 2 – Kệ sách A2 (Kinh tế vĩ mô)",
    status: "Sẵn có (Còn 42 cuốn)",
    image: "image/kinh tế vĩ mô.jpg"
  },
  "tu-tuong-ho-chi-minh": {
    title: "Giáo trình Tư tưởng Hồ Chí Minh",
    author: "PSG.TS Mạc Văn Tùng",
    publisher: "Nhà xuất bản Chính trị quốc gia",
    type: "Giáo trình",
    genre: "Chính trị",
    desc: "Giáo trình giới thiệu tóm lược các nội dung chính trong tư tưởng Hồ Chí Minh.",
    summary: "Cuốn sách hệ thống hóa tư tưởng Hồ Chí Minh theo từng chủ đề: đạo đức cách mạng, lãnh đạo, dân chủ, và phát triển bền vững. Phân tích nguyên lý, giá trị và ứng dụng trong bối cảnh Việt Nam hiện đại. Kèm trích dẫn nguyên tác và bình luận chuyên sâu từ các nhà nghiên cứu. Thích hợp cho sinh viên, cán bộ và người đọc quan tâm đến lý luận chính trị.",
    location: "Tầng 1 – Kệ sách C1 (Chính trị)",
    status: "Sẵn có (Còn 41 cuốn)",
    image: "image/gt tử tưởng HCM.jpg"
  },
  "dai-hoc-khoi-nghiep": {
    title: "Đại học Khởi nghiệp",
    author: "CEO Đặng Minh Quân",
    publisher: "Nhà xuất bản Doanh nhân",
    type: "Khác",
    genre: "Khởi nghiệp",
    desc: "Chia sẻ kinh nghiệm khởi nghiệp, xây dựng ý tưởng và phát triển doanh nghiệp.",
    summary: "Cuốn sách là cẩm nang thực chiến cho những người muốn khởi nghiệp từ con số 0. Bao gồm phương pháp xác định vấn đề, tìm ý tưởng và xác định khách hàng mục tiêu. Hướng dẫn xây dựng MVP, thử nghiệm thị trường và gọi vốn khởi sự. Cung cấp các checklist, mẫu kế hoạch và ví dụ từ startup Việt Nam.",
    location: "Tầng 2 – Kệ sách K1 (Khởi nghiệp)",
    status: "Sẵn có (Còn 46 cuốn)",
    image: "image/Đại học khởi nghiệp.jpg"
  },
  "nhung-cam-ky": {
    title: "Những Cấm Kỵ",
    author: "Phạm Ái Minh",
    publisher: "Nhà xuất bản Văn hóa",
    type: "Khác",
    genre: "Phát triển bản thân",
    desc: "Những điều nên và không nên trong giao tiếp, làm việc và xây dựng mối quan hệ.",
    summary: "Cuốn sách liệt kê những sai lầm phổ biến trong giao tiếp và cách tránh chúng. Cung cấp kỹ thuật lắng nghe, phản hồi và xây dựng niềm tin trong công việc. Kèm các tình huống thực tế và hướng giải quyết cụ thể. Giúp bạn cải thiện mối quan hệ cá nhân và chuyên nghiệp từng ngày.",
    location: "Tầng 1 – Kệ sách P1 (Kỹ năng)",
    status: "Sẵn có (Còn 44 cuốn)",
    image: "image/những cấm kỵ.jpg"
  },
  "tinh-hoa-kinh-te-hoc": {
    title: "Tinh Hoa Kinh Tế Học",
    author: "Paul Krugman",
    publisher: "Nhà xuất bản Kinh tế",
    type: "Sách tham khảo",
    genre: "Kinh tế học",
    desc: "Tổng hợp những lý thuyết kinh tế học quan trọng qua các thời kỳ.",
    summary: "Cuốn sách khám phá những đóng góp lớn nhất trong lịch sử kinh tế học từ Adam Smith đến hiện đại. Giải thích các mô hình lý thuyết đồng thời phân tích ứng dụng trong chính sách công và thị trường toàn cầu. Bao gồm bình luận về khủng hoảng tài chính và chính sách tiền tệ. Hướng người đọc xây dựng tư duy phản biện khi đọc số liệu kinh tế.",
    location: "Tầng 2 – Kệ sách A1 (Kinh tế học)",
    status: "Sẵn có (Còn 45 cuốn)",
    image: "image/tinh hoa kinh tế học.jpg"
  },
  "lich-su-dang": {
    title: "Lịch sử Đảng",
    author: "Bộ Giáo dục và Đào tạo",
    publisher: "Nhà xuất bản Chính trị quốc gia",
    type: "Nghiên cứu khoa học",
    genre: "Lịch sử",
    desc: "Tổng hợp các sự kiện quan trọng trong lịch sử Đảng Cộng sản Việt Nam.",
    summary: "Sách trình bày chi tiết các mốc lịch sử quan trọng, các nhân vật chủ chốt và các giai đoạn phát triển của Đảng. Phân tích bối cảnh chính trị – xã hội của từng thời kỳ và những quyết sách định hướng. Có phần bình luận về vai trò của Đảng trong tiến trình xây dựng đất nước. Giúp độc giả nhận diện bài học từ quá khứ và định hướng tương lai.",
    location: "Tầng 1 – Kệ sách L1 (Lịch sử)",
    status: "Sẵn có (Còn 43 cuốn)",
    image: "image/gt LSD.jpg"
  },
  "nguyen-ly-tiep-thi": {
    title: "Nguyên lý Tiếp thị",
    author: "Philip Kotler",
    publisher: "Nhà xuất bản Marketing",
    type: "Giáo trình",
    genre: "Marketing",
    desc: "Giáo trình giới thiệu các nguyên lý cơ bản của tiếp thị hiện đại.",
    summary: "Cung cấp lộ trình chi tiết xây dựng chiến lược tiếp thị, từ phân tích thị trường đến đo lường hiệu quả, với ví dụ thực tế từ doanh nghiệp.",
    location: "Tầng 2 – Kệ sách M1 (Marketing)",
    status: "Sẵn có (Còn 42 cuốn)",
    image: "image/nguyên lý tiếp thị.jpg"
  },
  "doi-mat-tu-ban": {
    title: "Đối mặt Tư bản",
    author: "Philip Kotler",
    publisher: "Nhà xuất bản Kinh tế",
    type: "Nghiên cứu khoa học",
    genre: "Kinh tế",
    desc: "Phân tích những thách thức của các nền kinh tế trong bối cảnh tư bản toàn cầu.",
    summary: "Phân tích sâu bối cảnh toàn cầu, tác động của tư bản và chiến lược thích nghi cho các nền kinh tế đang phát triển trong thế kỷ 21.",
    location: "Tầng 2 – Kệ sách A2 (Kinh tế vĩ mô)",
    status: "Sẵn có (Còn 44 cuốn)",
    image: "image/đối mặt tư bản.jpg"
  }
};